<!DOCTYPE html>
<html>

<head>
    <title></title>
    <?php require("include/meta.phtml"); ?>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.0/jquery.min.js"></script>
    <script src="https://cdn.tailwindcss.com"></script>
    <!-- <link rel="stylesheet" href="style.css"> -->
</head>

<body>
<div class="container flex w-screen">
    <div class="flex flex-col w-1/5 h-screen sidebar bg-slate-700">
      <?php require('include/adminSidebar.phtml'); ?>
    </div>

    <div class="flex flex-col w-4/5 pl-20 content">
      <?php require($VIEW); ?>
    </div>
  </div>
</body>

</html>