<!DOCTYPE html>
<html>

<head>
    <title></title>
    <?php require("include/meta.phtml"); ?>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.0/jquery.min.js"></script>
</head>

<body>
    <div id="topbar">
        <span class="logo">Supper Ship</span>
        <span>
            <?php
            if (isset($_SESSION["IsLogined"]) && $_SESSION["IsLogined"] == True) {
                $username = $_SESSION["UserName"];
                echo "<span class='username'>Xin chào <strong>$username</strong> <span style='color:white;'>|</span></span>";
            } else
                echo ' <span class="login">
                <a href="index.php?action=login&role">Đăng nhập</a> <span style="color:white;">|</span>
            </span>';
            ?>

            <?php
            if (isset($_SESSION["IsLogined"]) && $_SESSION["IsLogined"] == True) {
                $username = $_SESSION["UserName"];
                echo " <span class='logout' > <a href='index.php?action=logout'> Đăng xuất</a>
                </span>";
            } else
                echo ' <span class="login">
                <a href="index.php?action=register&role">Đăng ký</a>
            </span>';
            ?>

        </span>

    </div>
    <div id="wrapper">
        <div id="smallbar"></div>
        <div id="content" class="d-flex">
            <div id="sidebar">
                <?php require("include/sidebar.phtml"); ?>
            </div>

            <div id="main">
                <?php require($VIEW); ?>
            </div>

        </div>
        <div id="footer"></div>
    </div>
    <input id="main-role" type="hidden" value=<?= $role ?> />
</body>

<script type="text/javascript">
    var newOrderByShipperInterval
    let getNewOrderByShipper = () => {
        $.ajax({
            type: "GET",
            url: `index.php?action=get-new-order-by-shipper`,
            // dataType: "json",
            contentType: "json",
            success: function(response) {
                if (!response) {
                    return
                }
                let data = JSON.parse(response);
                if (data.success && data.message === "success") {
                    if (confirm(`Có đơn hàng mới với giá trị đơn: ${data.data?.total_cost}?. Bạn có muốn nhận đơn này?`) === true) {
                        $.ajax({
                            type: "POST",
                            url: `index.php?action=shipper-update-order-status`,
                            data: {
                                id: data.data._id,
                                status: "2"
                            },
                            success: function(res) {
                                if (res) {

                                    if (confirm("Cập nhật trạng thái đơn hàng thành công")) {

                                        window.location.replace("index.php?action=delivering")
                                    } else {
                                        window.location.replace("index.php?action=delivering")

                                    }
                                }

                            }
                        });
                    } else {
                        $.ajax({
                            type: "POST",
                            url: `index.php?action=shipper-update-order-status`,
                            data: {
                                id: data.data._id,
                                status: "-2"
                            },
                            success: function(res) {
                                if (res) {

                                    if (confirm("Cập nhật trạng thái đơn hàng thành công")) {

                                        window.location.replace("index.php?action=shipping-history")
                                    } else {
                                        window.location.replace("index.php?action=shipping-history")

                                    }
                                }

                            }
                        });
                    }
                }

            }
        });
    }

    $(document).ready(function() {

        const role = $("#main-role")[0].value
        console.log("zxc", role)
        if (role.includes("shipper")) {
            newOrderByShipperInterval = setInterval(getNewOrderByShipper, 5000)
        } else {
            clearInterval(newOrderByShipperInterval)
        }
    });
</script>

</html>