<?php
if (!empty($data)) {
    foreach ($data->items as $key=>$value) {
?>
<div class="product-item">
    <form method="post" action="index.php?action=addToCart">
        <div class="product-image"><img src=""></div>
        <div class="product-tile-footer">
            <div class="product-title"><?php echo $value->name; ?></div>
            <div class="product-price"><?php echo $value->unit_price ."VND"; ?></div>
            <div class="cart-action">
                <input type="number" class="product-quantity" name="quantity" value="1" size="2" />
                <input type="submit" value="Add to Cart" class="btnAddAction" /></div>
        </div>
    </form>
</div>
<?php
    }
}
?>


