<?php
define("ORDER_STATUS_CUSTOMER_DO_NOT_RECEIVE_ORDER", "-4");
define("ORDER_STATUS_SHIP_FAILED", "-3");
define("ORDER_STATUS_SHIPPER_DO_NOT_RECEIVE_ORDER", "-2");
define("ORDER_STATUS_SHOP_DO_NOT_RECEIVE_ORDER", "-1");
define("ORDER_STATUS_NEW", "0");
define("ORDER_STATUS_SHOP_ACCEPT_ORDER", "1");
define("ORDER_STATUS_SHIPPER_ACCEPT_ORDER", "2");
define("ORDER_STATUS_SHIP_SUCCESS", "3");
define("ORDER_STATUS_CUSTOMER_ACCEPT_ORDER", "4");

?>