<?php
$API = new API();
$url = "http://localhost:3000/api/shop/getAllProduct";
$method = "GET";
$payload = array();
$result = $API->CallAPI($method, $url, $payload);

foreach ($result->data as $row) {
    echo "<option value='$row->_id'>".$row->name."</option>";
}
?>

<div key={product._id} className="card">
    <Link to={`/product/${product._id}`}>
    <img className="medium" src={product.image} alt={product.name} />
    </Link>
    <div className="card-body">
        <Link to={`/product/${product._id}`}>
        <h2>{product.name}</h2>
        </Link>
        <Rating rating={product.rating} numReviews={product.numReviews} />
        <div className="price">{product.price}$</div>
    </div>
</div>