<table class="w-full table-auto">
    <thead>
    <tr>
        <th class="border border-x-0 border-slate-600">STT</th>
        <th class="border border-x-0 border-slate-600">Tổng sản phầm</th>
        <th class="border border-x-0 border-slate-600">Tổng tiền</th>
        <th class="border border-x-0 border-slate-600">Trạng thái</th>
        <th class="border border-x-0 border-slate-600">Cập nhật sản phẩm</th>

    </tr>
    </thead>
    <tbody>
    <?php
    $stt = 1;
    foreach($data as $item) {
        echo "<tr>";
        echo "<td class='py-3 text-center border border-x-0 border-slate-600'>$stt
                    <a  target='_blank' href='index.php?action=shipping-order-detail&id=<?=$item->_id ?>' class='decoration-none' class='border border-x-0 border-slate-600'> 
                    <?= $item->_id ?>
              </a>
              </td>";
        echo "<td class='py-3 text-center border border-x-0 border-slate-600'>$item->total_product</td>";
        echo "<td class='py-3 text-center border border-x-0 border-slate-600'>$item->total_cost VNĐ</td>";
        echo "<td class='py-3 text-center border border-x-0 border-slate-600'>$item->created_at</td>";
        echo "<td class='py-3 text-center border border-x-0 border-slate-600'>$item->updated_at</td>";
        if($item->status == 0) {
            echo "<td class='py-3 text-center border border-x-0 border-slate-600'><span class='text-green-500'>Chưa xác nhận</span></td>";
        } else if ($item->status == 1) {
            echo "<td class='py-3 text-center border border-x-0 border-slate-600'><span class='text-red-500'>Đã xác nhận</span></td>";
        }else if ($item->status == 2) {
            echo "<td class='py-3 text-center border border-x-0 border-slate-600'><span class='text-red-500'>Shipper nhận đơn</span></td>";
        }else if ($item->status == 3) {
            echo "<td class='py-3 text-center border border-x-0 border-slate-600'><span class='text-red-500'>Shipper giao hàng thành công</span></td>";
        }else if ($item->status == 4) {
            echo "<td class='py-3 text-center border border-x-0 border-slate-600'><span class='text-red-500'>Khách hàng đã nhận hàng</span></td>";
        }
//        echo "<td class='py-3 text-center border border-x-0 border-slate-600'>$item->status</td>";
        echo "<td class='py-3 text-center border border-x-0 border-slate-600'>
               <a  href='index.php?action=shop-update-order-status&id=$item->_id' class='decoration-none'> 
                    <?= $item->_id ?>
                    <div>Accept</div>
              </a>
               </td>";
        $stt = $stt + 1;
    }
    ?>
    </tbody>
</table>
<div class="mb-5 paging">
    <div class="mx-24 current-page">
        Trang hiện tại: <?= $currentPage ?></span>
    </div>
    <?php

    for ($i = 1; $i <= ceil($total / (10 * 1.0)); $i++) {
    ?>
    <span class="pointer paging-item" onclick="get(<?= $i ?>)"><?= $i ?></span>
<?php
}
?>