<?php
require_once("constant.php");

?>

    <script type="text/javascript">
        let updateStatus = (id, status) => {
            switch (status) {
                case "3":
                    if (confirm("Hoàn tất đơn hàng ?")) {
                        $.post({
                            url: `index.php?action=shop-update-order-status`,
                            data: {
                                id,
                                status

                            },
                            success: (res) => {
                                if (res) {

                                    if (confirm("Cập nhật trạng thái đơn hàng thành công")) {

                                        window.location.replace("index.php?action=shipping-history")
                                    } else {
                                        window.location.replace("index.php?action=shipping-history")

                                    }
                                }
                            }
                        });
                    }
                    break;
                case "-3":
                    if (confirm("Giao hàng thất bại ?")) {
                        $.post({
                            url: `index.php?action=shop-update-order-status`,
                            data: {
                                id,
                                status

                            },
                            success: (res) => {
                                if (res) {

                                    if (confirm("Cập nhật trạng thái đơn hàng thành công")) {

                                        window.location.replace("index.php?action=shipping-history")
                                    } else {
                                        window.location.replace("index.php?action=shipping-history")

                                    }
                                }
                            }
                        });
                    }
                    break;
                default:
                    break;
            }


        }
    </script>
    <h1>Chi tiết đơn hàng</h1>
    <hr />
<?php if ($data == null && $_REQUEST["action"] != "delivering") : ?>
    <div class="mt-24">Không tồn tại đơn hàng</div>
<?php elseif ($data == null && $_REQUEST["action"] == "delivering") : ?>
    <div class="mt-24">Không có đơn đang giao</div>
<?php elseif ($data != null) : ?>

    <div id="search-advance" class="mt-24">

        <div class="general-info d-flex justify-content-space-between">

            <div class="d-flex flex-column">
                <div class="d-flex justify-content-space-between align-items-space-between flex-column">
                    <label for="search-order-id"><b>ID đơn hàng</b> </label> <br />

                    <div class="d-flex align-items-center" style="height: 35px;"><?= $data->_id ?></div>

                </div>
                <br />
                <div class="d-flex justify-content-space-between align-items-space-between flex-column">
                    <label for="search-order-id"><b>Tên khách</b> </label> <br />

                    <div class="d-flex align-items-center"><?= $data->customer_info->full_name ?></div>

                </div>
                <br />
                <div class="d-flex justify-content-space-between align-items-space-between flex-column">
                    <label for="search-order-id"><b>Tổng sản phẩm</b> </label> <br />

                    <div class="d-flex align-items-center"><?= $data->total_product ?></div>

                </div>

            </div>
            <div class="d-flex  flex-column">
                <div class="d-flex justify-content-space-between align-items-space-between flex-column ">
                    <label for="search-from-date"><b>Ngày</b> </label>
                    <br />

                    <div class="d-flex align-items-center" style="height: 35px;"><?= $data->created_at ?></div>

                </div>
                <br />
                <div class="d-flex justify-content-space-between align-items-space-between flex-column ">
                    <label for="search-from-date"><b>Địa chỉ giao hàng</b> </label>
                    <br />

                    <div class="d-flex align-items-center"><?= $data->customer_info->address ?></div>

                </div>
                <br />
                <div class="d-flex justify-content-space-between align-items-space-between flex-column">
                    <label for="search-order-id"><b>Tổng tiền</b> </label> <br />

                    <div class="d-flex align-items-center"><?= $data->total_cost ?></div>

                </div>

            </div>
            <div class="d-flex  flex-column">

                <div class="d-flex justify-content-space-between align-items-space-between flex-column ">
                    <label for="search-to-date"><b>Trạng thái</b> </label> <br />
                    <?= $data->status == ORDER_STATUS_SHIP_SUCCESS ?
                        "<span class='d-flex justify-center' style='width: 100px; border-radius: 8px; padding: 8px; background: #2cb104; color: white;'>Thành công</span>"
                        : ($data->status == ORDER_STATUS_SHIPPER_ACCEPT_ORDER ? "<span class='d-flex justify-center' style='width: 100px; border-radius: 8px; padding: 8px; background: #4b71cf; color: white;'>Đang giao</span>" :  "<span class='d-flex justify-center' style='width: 100px; border-radius: 8px; padding: 8px; background: #ff6464; color: white;'>Thất bại</span>") ?>

                </div>
                <br />
                <div class="d-flex justify-content-space-between align-items-space-between flex-column ">
                    <label for="search-to-date"><b>Số điện thoại</b> </label> <br />
                    <div class="d-flex align-items-center"><?= $data->customer_info->phone ?></div>
                </div>
                <br />
                <?php if ($data->status == ORDER_STATUS_SHIPPER_ACCEPT_ORDER) :  ?>
                    <div class="d-flex justify-content-space-between align-items-space-between flex-column">
                        <label for="search-order-id"><b>Thao tác</b> </label> <br />

                        <div class="d-flex">

                            <span>
                                <button type="default" class="danger" onclick="updateStatus( `<?php echo $data->_id ?>`, `-3`)">Giao thất bại</button>
                            </span>
                            <span class="ml-8">
                                <button type="default" onclick="updateStatus( `<?php echo $data->_id ?>`, '3')" class="success">Hoàn tất đơn</button>

                            </span>
                        </div>

                    </div>
                <?php endif ?>
            </div>

        </div>
        <table class="custom-table mt-24">
            <tr style="height: 40px">

                <th style="width: 250px">
                    Tên sản phẩm
                </th>
                <th style="width: 250px">
                    Mô tả
                </th>
                <th style="text-align: center;width: 150px">
                    Giá
                </th>
                <th style="text-align: center;width: 150px">
                    Số lượng
                </th>
                <th style="text-align: center;width: 150px">
                    Thành tiền
                </th>

            </tr>


            <?php


            foreach ($data->products as $key => $item) {
                ?>


                <tr style="height: 40px">

                    <td>
                        <?= $item->name ?>
                    </td>
                    <td>
                        <?= $item->description ?>
                    </td>
                    <td style="text-align: center;">
                        <?= $item->unit_price ?>
                    </td>
                    <td style="text-align: center;">
                        <?= $item->quantity ?>
                    </td>
                    <td style="text-align: center;">
                        <?= $item->quantity *  $item->unit_price ?>
                    </td>
                </tr>

                <?php
            }
            ?>
        </table>
    </div>
    <script type="text/javascript">
        let get = function(page) {

            let limit = 10;
            let offset = limit * page - limit;

            $.post({
                url: `index.php?action=shopListShipper`,
                data: {
                    limit,
                    offset,
                },
                success: function(response) {
                    $("#shipper-list").html(response)
                }
            });


        };

        $(document).ready(function() {
            get(1)
        });
    </script>
    <div class="flex justify-between w-full p-5 header">
        <h2>CHỌN NGƯỜI GIAO HÀNG</h2>
    </div>

    <div class="flex justify-start">
        <!-- search form -->
        <div class="px-5 mb-2 xl:w-96">
            <div class="relative flex items-stretch w-full mb-4 input-group">
                <input type="search" class="form-control relative flex-auto min-w-0 block w-full px-3 py-1.5 text-base font-normal text-gray-700 bg-white bg-clip-padding border border-solid border-gray-300 rounded transition ease-in-out m-0 focus:text-gray-700 focus:bg-white focus:border-blue-600 focus:outline-none" placeholder="Search" aria-label="Search" aria-describedby="button-addon2">
                <button class="btn inline-block px-6 py-2.5 bg-blue-600 text-white font-medium text-xs leading-tight uppercase rounded shadow-md hover:bg-blue-700 hover:shadow-lg focus:bg-blue-700  focus:shadow-lg focus:outline-none focus:ring-0 active:bg-blue-800 active:shadow-lg transition duration-150 ease-in-out flex items-center" type="button" id="button-addon2">
                    <svg aria-hidden="true" focusable="false" data-prefix="fas" data-icon="search" class="w-4" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512">
                        <path fill="currentColor" d="M505 442.7L405.3 343c-4.5-4.5-10.6-7-17-7H372c27.6-35.3 44-79.7 44-128C416 93.1 322.9 0 208 0S0 93.1 0 208s93.1 208 208 208c48.3 0 92.7-16.4 128-44v16.3c0 6.4 2.5 12.5 7 17l99.7 99.7c9.4 9.4 24.6 9.4 33.9 0l28.3-28.3c9.4-9.4 9.4-24.6.1-34zM208 336c-70.7 0-128-57.2-128-128 0-70.7 57.2-128 128-128 70.7 0 128 57.2 128 128 0 70.7-57.2 128-128 128z"></path>
                    </svg>
                </button>
            </div>
        </div>
    </div>
    <div class="flex flex-col justify-between px-5 ds" id="shipper-list"></div>
<?php endif ?>