<script type="text/javascript">
    const updateOrder = function(shipper_id){
        const queryString = window.location.search;
        const urlParams = new URLSearchParams(queryString);
        const order_id = urlParams.get('id')
        let data =  {
            shipper_id,
            order_id
        };
        $.post({
            url: `index.php?action=shopUpdateOrder`,
            data: {
                shipper_id,
                order_id
            },
            success: function(response) {
                $("#health-history").html(response)

            }
        });

    };

    const test = ()=>{
        console.log('abc');
    }

    $(document).ready(function() {

        const now = new Date().toISOString().substring(0, 10);
        // $("#search-from-date")[0].val = now;
        // $("#search-to-date")[0].val = now;
        document.getElementById('search-from-date').value = now;
        document.getElementById('search-to-date').value = now;

        let from = $("#search-from-date")[0].value;
        let to = $("#search-to-date")[0].value;
    });
</script>
<table class="w-full table-auto">
    <thead>
    <tr>
        <th class="border border-x-0 border-slate-600">STT</th>
        <th class="border border-x-0 border-slate-600">ID</th>
        <th class="border border-x-0 border-slate-600">Họ và tên</th>
        <th class="border border-x-0 border-slate-600">Địa chỉ</th>
        <th class="border border-x-0 border-slate-600">Email</th>
        <th class="border border-x-0 border-slate-600">
            Số điện thoại
        </th >
        <th class="border border-x-0 border-slate-600">
            Chọn shipper
        </th>

    </tr>
    </thead>
    <tbody>
    <?php
    $stt = 1;
    foreach($data as $item) {
        echo "<form method='post' class='mt-24'>";
        echo "<tr>";
        echo "<td class='py-3 text-center border border-x-0 border-slate-600'>";
        echo $stt;
        echo "</td>";
        echo "<td class='py-3 text-center border border-x-0 border-slate-600'>";
        echo $item->_id;
        echo "</td>";
        echo "<td class='py-3 text-center border border-x-0 border-slate-600'>";
        echo $item->full_name;
        echo "</td>";
        echo "<td class='py-3 text-center border border-x-0 border-slate-600'>";
        echo $item->address;
        echo "</td>";
        echo "<td class='py-3 text-center border border-x-0 border-slate-600'>";
        echo $item->email;
        echo "</td>";
        echo "<td class='py-3 text-center border border-x-0 border-slate-600'>";
        echo $item->phone;
        echo "</td>";
        echo "<td class='py-3 text-center border border-x-0 border-slate-600'>";
        echo "<form>";
        echo '<button name="subject" type="button" onclick="updateOrder(\''.$item->_id.'\')" style="width: 100px; border-radius: 8px; padding: 8px; background: #ff6464; color: white;" >Pick shipper</button>';
        echo "</form>";
        $stt = $stt + 1;
        echo "</td>";
    }
    ?>
    </tbody>
</table>
<div class="mb-5 paging">
    <div class="mx-24 current-page">
        Trang hiện tại: <?= $currentPage ?></span>
    </div>
    <?php

    for ($i = 1; $i <= ceil($total / (10 * 1.0)); $i++) {
    ?>
    <span class="pointer paging-item" onclick="get(<?= $i ?>)"><?= $i ?></span>
<?php
}
?>