<?php
require_once("constant.php");

?>

<script type="text/javascript">
</script>
<h1>Chi tiết đơn hàng</h1>
<hr />

<div id="search-advance" class="mt-24">

    <div class="general-info d-flex justify-content-space-between">

        <div class="d-flex flex-column">
            <div class="d-flex justify-content-space-between align-items-space-between flex-column">
                <label for="search-order-id"><b>ID đơn hàng</b> </label> <br />

                <div class="d-flex align-items-center"><?= $data->_id ?></div>

            </div>
            <br />
            <div class="d-flex justify-content-space-between align-items-space-between flex-column">
                <label for="search-order-id"><b>Tên khách</b> </label> <br />

                <div class="d-flex align-items-center"><?= $data->customer_info->full_name ?></div>

            </div>
            <br />
            <div class="d-flex justify-content-space-between align-items-space-between flex-column">
                <label for="search-order-id"><b>Tổng sản phẩm</b> </label> <br />

                <div class="d-flex align-items-center"><?= $data->total_product ?></div>

            </div>

        </div>
        <div class="d-flex  flex-column">
            <div class="d-flex justify-content-space-between align-items-space-between flex-column ">
                <label for="search-from-date"><b>Ngày</b> </label>
                <br />

                <div class="d-flex align-items-center"><?= $data->created_at ?></div>

            </div>
            <br />
            <div class="d-flex justify-content-space-between align-items-space-between flex-column ">
                <label for="search-from-date"><b>Địa chỉ giao hàng</b> </label>
                <br />

                <div class="d-flex align-items-center"><?= $data->customer_info->address ?></div>

            </div>
            <br />
            <div class="d-flex justify-content-space-between align-items-space-between flex-column">
                <label for="search-order-id"><b>Tổng tiền</b> </label> <br />

                <div class="d-flex align-items-center"><?= $data->total_cost ?></div>

            </div>
        </div>
        <div class="d-flex  flex-column">

            <div class="d-flex justify-content-space-between align-items-space-between flex-column ">
                <label for="search-to-date"><b>Trạng thái</b> </label> <br />
                <?= $data->status == ORDER_STATUS_SHIP_SUCCESS ?
                    "<span class='d-flex justify-center' style='border-radius: 8px; padding: 8px; background: #2cb104; color: white;'>Thành công</span>"
                    : ($data->status == ORDER_STATUS_SHIPPER_ACCEPT_ORDER ? "<span class='d-flex justify-center' style='border-radius: 8px; padding: 8px; background: #4b71cf; color: white;'>Đang giao</span>" :  "<span class='d-flex justify-center' style='border-radius: 8px; padding: 8px; background: #ff6464; color: white;'>Thất bại</span>") ?>

            </div>
            <br />
            <div class="d-flex justify-content-space-between align-items-space-between flex-column ">
                <label for="search-to-date"><b>Số điện thoại</b> </label> <br />
                <div class="d-flex align-items-center"><?= $data->customer_info->phone ?></div>
            </div>
        </div>

    </div>
    <table class="custom-table mt-24">
        <tr style="height: 40px">

            <th style="width: 250px">
                Tên sản phẩm
            </th>
            <th style="width: 250px">
                Mô tả
            </th>
            <th style="text-align: center;width: 150px">
                Giá
            </th>
            <th style="text-align: center;width: 150px">
                Số lượng
            </th>
            <th style="text-align: center;width: 150px">
                Thành tiền
            </th>

        </tr>


        <?php


        foreach ($data->products as $key => $item) {
        ?>


            <tr style="height: 40px">

                <td>
                    <?= $item->name ?>
                </td>
                <td>
                    <?= $item->description ?>
                </td>
                <td style="text-align: center;">
                    <?= $item->unit_price ?>
                </td>
                <td style="text-align: center;">
                    <?= $item->quantity ?>
                </td>
                <td style="text-align: center;">
                    <?= $item->quantity *  $item->unit_price?>
                </td>
            </tr>

        <?php
        }
        ?>
    </table>
</div>