
<div class="flex justify-between w-full p-5 header">
  <h2>ĐÁNH GIÁ CỦA NGƯỜI DÙNG VỀ HỆ THỐNG</h2>
</div>

<div class="flex justify-start">
  <!-- search form -->
  <div class="px-5 mb-2 xl:w-96">
    <div class="relative flex items-stretch w-full mb-4 input-group">
      <input
        type="search"
        class="form-control relative flex-auto min-w-0 block w-full px-3 py-1.5 text-base font-normal text-gray-700 bg-white bg-clip-padding border border-solid border-gray-300 rounded transition ease-in-out m-0 focus:text-gray-700 focus:bg-white focus:border-blue-600 focus:outline-none"
        placeholder="Search"
        aria-label="Search"
        aria-describedby="button-addon2"
      />
      <button
        class="btn inline-block px-6 py-2.5 bg-blue-600 text-white font-medium text-xs leading-tight uppercase rounded shadow-md hover:bg-blue-700 hover:shadow-lg focus:bg-blue-700 focus:shadow-lg focus:outline-none focus:ring-0 active:bg-blue-800 active:shadow-lg transition duration-150 ease-in-out flex items-center"
        type="button"
        id="button-addon2"
      >
        <svg
          aria-hidden="true"
          focusable="false"
          data-prefix="fas"
          data-icon="search"
          class="w-4"
          role="img"
          xmlns="http://www.w3.org/2000/svg"
          viewBox="0 0 512 512"
        >
          <path
            fill="currentColor"
            d="M505 442.7L405.3 343c-4.5-4.5-10.6-7-17-7H372c27.6-35.3 44-79.7 44-128C416 93.1 322.9 0 208 0S0 93.1 0 208s93.1 208 208 208c48.3 0 92.7-16.4 128-44v16.3c0 6.4 2.5 12.5 7 17l99.7 99.7c9.4 9.4 24.6 9.4 33.9 0l28.3-28.3c9.4-9.4 9.4-24.6.1-34zM208 336c-70.7 0-128-57.2-128-128 0-70.7 57.2-128 128-128 70.7 0 128 57.2 128 128 0 70.7-57.2 128-128 128z"
          ></path>
        </svg>
      </button>
    </div>
  </div>
</div>
<div class="flex justify-between px-5 ds">
  <table class="w-full table-auto">
    <thead>
      <tr>
        <th class="border border-x-0 border-slate-600">ID sản phẩm</th>
        <th class="border border-x-0 border-slate-600">Họ và tên</th>
        <th class="border border-x-0 border-slate-600">Vai trò</th>
        <th class="border border-x-0 border-slate-600">Nội dung</th>
        <th class="border border-x-0 border-slate-600">Hành động</th>
      </tr>
    </thead>
    <tbody>

    <?php 
          foreach ($data as $item) 
          {   
            echo "<tr>";
            echo "<td class='py-3 text-center border border-x-0 border-slate-600'>";
              echo $item->product->_id;
            echo "</td>";
           echo "<td class='py-3 text-center border border-x-0 border-slate-600'>";
           echo $item->author->full_name;
            echo "</td>";
            echo "<td class='py-3 text-center border border-x-0 border-slate-600'>";
              echo "Người mua";
            echo "</td>";
            echo "<td class='py-3 text-center border border-x-0 border-slate-600'>";
            echo $item->content;
            echo "</td>";
            echo "<td class='py-3 text-center border border-x-0 border-slate-600'>";
              echo "<button class='px-4 py-2 font-bold text-white bg-blue-500 rounded hover:bg-blue-700'>";
                echo "Reply";
              echo "</button>";
            echo "</td>";
          echo "</tr>";
          }
        ?>
    </tbody>
  </table>
</div>
