<script type="text/javascript">
    const get = function(page) {

       let limit = 10;
       let offset = limit * page - limit;

        $.post({
            url: `index.php?action=listReview`,
            data: {
              limit,
              offset, 
            },
            success: function(response) {
                $("#reviews-list").html(response)
            }
        });


    };

    const reply = function(id) {
      console.log(123)
      const content = $(`#${id}`)[0].value;

      $.post({
            url: `index.php?action=replyComment`,
            data: {
              id,
              content,
            },
            success: function(response) {
              get(1)
            }
        });
    };

    $(document).ready(function() {
        get(1)
    });
</script>

<div class="flex justify-between w-full p-5 header">
  <h2>ĐÁNH GIÁ CỦA NGƯỜI DÙNG VỀ HỆ THỐNG</h2>
</div>

<div class="flex flex-col px-5 ds" id="reviews-list"></div>
