<div class="flex justify-between w-full p-5 header">
  <h2>TRANG CHỦ</h2>
  <h2>ADMIN</h2>
</div>

<div class="flex justify-between px-5 mt-10 overview">
  <div class="box-view">
    <h3>Cửa hàng</h3>
    <?php 
      echo "<span class='text-center text-sky-400'>$numOfStores</span>"
    ?>
  </div>
  <div class="box-view">
    <h3>Người mua</h3>
    <?php 
      echo "<span class='text-center text-sky-400'>$numOfCustomers</span>"
    ?>
  </div>
  <div class="box-view">
    <h3>Người vận chuyển</h3>
    <?php 
      echo "<span class='text-center text-sky-400'>$numOfShippers</span>"
    ?>
  </div>
  <div class="box-view">
    <h3>Khác</h3>
    <?php 
      echo "<span class='text-center text-sky-400'>$numOfReviews</span>"
    ?>
  </div>
</div>

<div class="w-full p-5 img"></div>
