
<table class="w-full table-auto">
    <thead>
      <tr>
        <th class="border border-x-0 border-slate-600">STT</th>
        <th class="border border-x-0 border-slate-600">Tên cửa hàng</th>
        <th class="border border-x-0 border-slate-600">Email</th>
        <th class="border border-x-0 border-slate-600">Số điện thoại</th>
        <th class="border border-x-0 border-slate-600">Hồ sơ đăng kí</th>
        <th class="border border-x-0 border-slate-600">Trạng thái</th>
      </tr>
    </thead>
    <tbody>
      <?php 
        $stt = 1;
        foreach($data as $item) {
        echo "<tr>";
        echo "<td class='py-3 text-center border border-x-0 border-slate-600'>$stt</td>";
        echo "<td class='py-3 text-center border border-x-0 border-slate-600'>$item->name ? </td>";
        echo "<td class='py-3 text-center border border-x-0 border-slate-600'>$item->email</td>";
        echo "<td class='py-3 text-center border border-x-0 border-slate-600'>$item->phone</td>";
        echo "<td class='py-3 text-center border border-x-0 border-slate-600'>$item->business_cert</td>";
        if($item->isActive == true) {
          echo "<td class='py-3 text-center border border-x-0 border-slate-600'><span class='text-green-500'>Đã duyệt</span></td>";
        } else {
          echo "<td class='py-3 text-center border border-x-0 border-slate-600'><span class='text-red-500'>Chờ xét duyệt</span></td>";
        }
        echo "</tr>";
        $stt = $stt + 1;
        }
      ?>
    </tbody>
  </table>
  <div class="mb-5 paging">
    <div class="mx-24 current-page">
        Trang hiện tại: <?= $currentPage ?></span>
    </div>
    <?php

    for ($i = 1; $i <= ceil($total / (10 * 1.0)); $i++) {
    ?>
        <span class="pointer paging-item" onclick="get(<?= $i ?>)"><?= $i ?></span>
    <?php
    }
    ?>