
<div class="flex justify-between w-full p-5 header">
  <h2>DANH SÁCH CỬA HÀNG</h2>
</div>

<div class="flex justify-start">
  <!-- search form -->
  <div class="px-5 mb-2 xl:w-96">
    <div class="relative flex items-stretch w-full mb-4 input-group">
      <input type="search" class="form-control relative flex-auto min-w-0 block w-full px-3 py-1.5 text-base font-normal text-gray-700 bg-white bg-clip-padding border border-solid border-gray-300 rounded transition ease-in-out m-0 focus:text-gray-700 focus:bg-white focus:border-blue-600 focus:outline-none" placeholder="Search" aria-label="Search" aria-describedby="button-addon2">
      <button class="btn inline-block px-6 py-2.5 bg-blue-600 text-white font-medium text-xs leading-tight uppercase rounded shadow-md hover:bg-blue-700 hover:shadow-lg focus:bg-blue-700  focus:shadow-lg focus:outline-none focus:ring-0 active:bg-blue-800 active:shadow-lg transition duration-150 ease-in-out flex items-center" type="button" id="button-addon2">
        <svg aria-hidden="true" focusable="false" data-prefix="fas" data-icon="search" class="w-4" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512">
          <path fill="currentColor" d="M505 442.7L405.3 343c-4.5-4.5-10.6-7-17-7H372c27.6-35.3 44-79.7 44-128C416 93.1 322.9 0 208 0S0 93.1 0 208s93.1 208 208 208c48.3 0 92.7-16.4 128-44v16.3c0 6.4 2.5 12.5 7 17l99.7 99.7c9.4 9.4 24.6 9.4 33.9 0l28.3-28.3c9.4-9.4 9.4-24.6.1-34zM208 336c-70.7 0-128-57.2-128-128 0-70.7 57.2-128 128-128 70.7 0 128 57.2 128 128 0 70.7-57.2 128-128 128z"></path>
        </svg>
      </button>
    </div>
  </div>
  <!-- filter box -->
  <div class="relative text-left">
    <div>
      <button type="button" class="inline-flex justify-center w-full px-4 py-2 text-sm font-medium text-gray-700 bg-white border border-gray-300 rounded-md shadow-sm hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-offset-gray-100 focus:ring-indigo-500" id="menu-button" aria-expanded="true" aria-haspopup="true">
        Bộ lọc
        <!-- Heroicon name: solid/chevron-down -->
        <svg class="w-5 h-5 ml-2 -mr-1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
          <path fill-rule="evenodd" d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z" clip-rule="evenodd" />
        </svg>
      </button>
    </div>
  </div>
    <!-- end filter box -->
</div>
<div class="flex flex-col justify-between px-5 mt-0 ds ">
  <table class="w-full table-auto">
      <thead>
        <tr>
          <th class="border border-x-0 border-slate-600">STT</th>
          <th class="border border-x-0 border-slate-600">Tên cửa hàng</th>
          <th class="border border-x-0 border-slate-600">Email</th>
          <th class="border border-x-0 border-slate-600">Địa chỉ</th>
          <th class="border border-x-0 border-slate-600">Số điện thoại</th>
          <th class="border border-x-0 border-slate-600">Hồ sơ đăng kí</th>
          <th class="border border-x-0 border-slate-600">Trạng thái</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td class="py-3 text-center border border-x-0 border-slate-600">1</td>
          <td class="py-3 text-center border border-x-0 border-slate-600">Bách hoá xanh</td>
          <td class="py-3 text-center border border-x-0 border-slate-600">bhxanh@gmail.com</td>
          <td class="py-3 text-center border border-x-0 border-slate-600">Ktx khu B ĐHQG</td>
          <td class="py-3 text-center border border-x-0 border-slate-600">098746753</td>
          <td class="py-3 text-center border border-x-0 border-slate-600"><a href="#">https://anh.com</a></td>
          <td class="py-3 text-center border border-x-0 border-slate-600"><span class="text-orange-300">Chờ xét duyệt</span></td>
        </tr>
        <tr>
          <td class="py-3 text-center border border-x-0 border-slate-600">1</td>
          <td class="py-3 text-center border border-x-0 border-slate-600">Bách hoá xanh</td>
          <td class="py-3 text-center border border-x-0 border-slate-600">bhxanh@gmail.com</td>
          <td class="py-3 text-center border border-x-0 border-slate-600">Ktx khu B ĐHQG</td>
          <td class="py-3 text-center border border-x-0 border-slate-600">098746753</td>
          <td class="py-3 text-center border border-x-0 border-slate-600"><a href="#">https://anh.com</a></td>
          <td class="py-3 text-center border border-x-0 border-slate-600"><span class="text-orange-300">Chờ xét duyệt</span></td>
        </tr>
        <tr>
          <td class="py-3 text-center border border-x-0 border-slate-600">1</td>
          <td class="py-3 text-center border border-x-0 border-slate-600">Bách hoá xanh</td>
          <td class="py-3 text-center border border-x-0 border-slate-600">bhxanh@gmail.com</td>
          <td class="py-3 text-center border border-x-0 border-slate-600">Ktx khu B ĐHQG</td>
          <td class="py-3 text-center border border-x-0 border-slate-600">098746753</td>
          <td class="py-3 text-center border border-x-0 border-slate-600"><a href="#">https://anh.com</a></td>
          <td class="py-3 text-center border border-x-0 border-slate-600"><span class="text-orange-300">Chờ xét duyệt</span></td>
        </tr>
        <tr>
          <td class="py-3 text-center border border-x-0 border-slate-600">1</td>
          <td class="py-3 text-center border border-x-0 border-slate-600">Bách hoá xanh</td>
          <td class="py-3 text-center border border-x-0 border-slate-600">bhxanh@gmail.com</td>
          <td class="py-3 text-center border border-x-0 border-slate-600">Ktx khu B ĐHQG</td>
          <td class="py-3 text-center border border-x-0 border-slate-600">098746753</td>
          <td class="py-3 text-center border border-x-0 border-slate-600"><a href="#">https://anh.com</a></td>
          <td class="py-3 text-center border border-x-0 border-slate-600"><span class="text-green-500">Đã duyệt</span></td>
        </tr>
        <tr>
          <td class="py-3 text-center border border-x-0 border-slate-600">1</td>
          <td class="py-3 text-center border border-x-0 border-slate-600">Bách hoá xanh</td>
          <td class="py-3 text-center border border-x-0 border-slate-600">bhxanh@gmail.com</td>
          <td class="py-3 text-center border border-x-0 border-slate-600">Ktx khu B ĐHQG</td>
          <td class="py-3 text-center border border-x-0 border-slate-600">098746753</td>
          <td class="py-3 text-center border border-x-0 border-slate-600"><a href="#">https://anh.com</a></td>
          <td class="py-3 text-center border border-x-0 border-slate-600"><span class="text-green-500">Đã duyệt</span></td>
        </tr>
        <tr>
          <td class="py-3 text-center border border-x-0 border-slate-600">1</td>
          <td class="py-3 text-center border border-x-0 border-slate-600">Bách hoá xanh</td>
          <td class="py-3 text-center border border-x-0 border-slate-600">bhxanh@gmail.com</td>
          <td class="py-3 text-center border border-x-0 border-slate-600">Ktx khu B ĐHQG</td>
          <td class="py-3 text-center border border-x-0 border-slate-600">098746753</td>
          <td class="py-3 text-center border border-x-0 border-slate-600"><a href="#">https://anh.com</a></td>
          <td class="py-3 text-center border border-x-0 border-slate-600"><span class="text-green-500">Đã duyệt</span></td>
        </tr>
        <tr>
          <td class="py-3 text-center border border-x-0 border-slate-600">1</td>
          <td class="py-3 text-center border border-x-0 border-slate-600">Bách hoá xanh</td>
          <td class="py-3 text-center border border-x-0 border-slate-600">bhxanh@gmail.com</td>
          <td class="py-3 text-center border border-x-0 border-slate-600">Ktx khu B ĐHQG</td>
          <td class="py-3 text-center border border-x-0 border-slate-600">098746753</td>
          <td class="py-3 text-center border border-x-0 border-slate-600"><a href="#">https://anh.com</a></td>
          <td class="py-3 text-center border border-x-0 border-slate-600"><span class="text-green-500">Đã duyệt</span></td>
        </tr>

      </tbody>
    </table>
</div>