
<table class="w-full table-auto">
    <thead>
      <tr>
        <th class="border border-x-0 border-slate-600">STT</th>
        <th class="border border-x-0 border-slate-600">Tên cửa hàng</th>
        <th class="border border-x-0 border-slate-600">Email</th>
        <th class="border border-x-0 border-slate-600">Số điện thoại</th>
        <th class="border border-x-0 border-slate-600">Hồ sơ đăng kí</th>
        <th class="border border-x-0 border-slate-600">Trạng thái</th>
        <th class="border border-x-0 border-slate-600">Lựa chọn</th>
      </tr>
    </thead>
    <tbody>
      <?php 
        $stt = 1;
        foreach($data as $item) {
          $item->business_cert = $item->business_cert ? $item->business_cert : "https://bizweb.dktcdn.net/100/384/422/files/image-007.jpg?v=1587640188630";
        echo "<tr>";
        echo "<td class='py-3 text-center border border-x-0 border-slate-600'>$stt</td>";
        echo "<td class='py-3 text-center border border-x-0 border-slate-600'>$item->name ? </td>";
        echo "<td class='py-3 text-center border border-x-0 border-slate-600'>$item->email</td>";
        echo "<td class='py-3 text-center border border-x-0 border-slate-600'>$item->phone</td>";
        echo "<td class='py-3 text-center border border-x-0 border-slate-600'><a href='$item->business_cert'>$item->business_cert</a></td>";
        if(isset($item->isActive) && $item->isActive == true) {
          echo "<td class='py-3 text-center border border-x-0 border-slate-600'><span class='text-green-500'>Đã duyệt</span></td>";
          echo "<td class='py-3 text-center border border-x-0 border-slate-600'>";
          echo "<button disabled opacity-25 class='px-4 py-2 font-bold rounded text-slate-400 bg-slate-600'>";
            echo "Duyệt";
          echo "</button>";
        echo "</td>";
        } else {
          echo "<td class='py-3 text-center border border-x-0 border-slate-600'><span class='text-red-500'>Chờ xét duyệt</span></td>";
          echo "<td class='py-3 text-center border border-x-0 border-slate-600'>";
          echo "<button onclick='updateStatus(\"$item->_id\")' class='px-4 py-2 font-bold text-white bg-blue-500 rounded hover:bg-blue-700'>";
            echo "Duyệt";
          echo "</button>";
        echo "</td>";
        }
       
        echo "</tr>";
             
        $stt = $stt + 1;
        }
      ?>
    </tbody>
  </table>
  <div class="mb-5 paging">
    <div class="mx-24 current-page">
        Trang hiện tại: <?= $currentPage ?></span>
    </div>
    <?php

    for ($i = 1; $i <= ceil($total / (10 * 1.0)); $i++) {
    ?>
        <span class="pointer paging-item" onclick="get(<?= $i ?>)"><?= $i ?></span>
    <?php
    }
    ?>