<table class="w-full table-auto">
      <thead>
        <tr>
          <th class="border border-x-0 border-slate-600">ID</th>
          <th class="border border-x-0 border-slate-600">Họ và tên</th>
          <th class="border border-x-0 border-slate-600">Địa chỉ</th>
          <th class="border border-x-0 border-slate-600">Email</th>
          <th class="border border-x-0 border-slate-600">Số điện thoại</th>
          <th class="border border-x-0 border-slate-600">Số đơn hàng mua</th>
        </tr>
      </thead>
      <tbody>
      <?php 
          foreach ($data as $item) 
          {
            $item->full_name = $item->full_name ? $item->full_name : "";
            $item->address = $item->address ? $item->address : "";
            echo "<tr>";
            echo "<td class='py-3 text-center border border-x-0 border-slate-600'>$item->_id</td>";
            echo "<td class='py-3 text-center border border-x-0 border-slate-600'>$item->full_name</td>";
            echo "<td class='py-3 text-center border border-x-0 border-slate-600'>$item->address</td>";
            echo "<td class='py-3 text-center border border-x-0 border-slate-600'>$item->email</td>";
            echo "<td class='py-3 text-center border border-x-0 border-slate-600'>$item->phone</td>";
            if($item->totalOrders > 0) {
              echo "<td class='py-3 text-center border border-x-0 border-slate-600'><span class='text-green-500'>$item->totalOrders</span></td>";
            } else {
              echo "<td class='py-3 text-center border border-x-0 border-slate-600'><span class='text-red-500'>$item->totalOrders</span></td>";
            }
            echo "</tr>";
           }
          ?>
       
      </tbody>
  </table>
    <div class="mb-5 paging">
    <div class="mx-24 current-page">
        Trang hiện tại: <?= $currentPage ?></span>
    </div>
    <?php

    for ($i = 1; $i <= ceil($total / (10 * 1.0)); $i++) {
    ?>
        <span class="pointer paging-item" onclick="get(<?= $i ?>)"><?= $i ?></span>
    <?php
    }
    ?>