<script type="text/javascript">
    const get = function(page) {

       let size = 10;

       const search = $("#search-text")[0].value;

        $.post({
            url: `index.php?action=cusListStore`,
            data: {
              size,
              page,
              search,
            },
            success: function(response) {
                $("#shop-list").html(response)
            }
        });


    };

    $(document).ready(function() {
        get(1)
    });
</script>
<div class="flex justify-between w-full p-5 header">
  <h2>DANH SÁCH CỬA HÀNG</h2>
</div>

<div class="flex justify-start">
  <!-- search form -->
  <div class="px-5 mb-2 xl:w-96">
    <div class="relative flex items-stretch w-full mb-4 input-group">
      <input type="text" id="search-text"  placeholder="Search" aria-label="Search" aria-describedby="button-addon2">
      <button onclick="get(1)" class="primary" type="button" id="button-addon2">
       Tìm
      </button>
    </div>
  </div>
</div>
<div class="flex flex-col justify-between px-5 ds" id="shop-list"></div>