    <h2 class="p-5 font-bold text-center text-white">ĐI CHỢ THUÊ</h2>
      <hr/>
      <ul class="w-full">
        <a href='index.php?action=admin'><div class="box hover:bg-slate-600 hover:text-white"><li>Trang chủ</li></div></a>
        <a href='index.php?action=viewStore'><div class="box hover:bg-slate-600 hover:text-white"><li>Cửa hàng</li></div></a>
        <a href='index.php?action=viewCustomer'><div class="box hover:bg-slate-600 hover:text-white"><li>Người mua</li></div></a>
        <a href='index.php?action=viewShipper'><div class="box hover:bg-slate-600 hover:text-white"><li>Người giao hàng</li></div></a>
        <a href='index.php?action=listReview'><div class="box hover:bg-slate-600 hover:text-white"><li>Đánh giá</li></div></a>
      </ul>
      <a href='index.php?action=logout'><div class="relative bottom-0 mt-10 text-red-300 box hover:bg-slate-600 hover:text-red-600">Đăng xuất</div></a>