<div class="sidebox">
    <h2>Các chức năng</h2>
    <?php if (isset($_SESSION["IsLogined"]) && $_SESSION["IsLogined"] == True && $_SESSION["role"] == "shipper"): ?>
        <div class="menu">
            <ul>
                <li>
                    <a href="index.php">Trang chủ</a>
                </li>
                <li>
                    <a href="index.php?action=shipping-history">Lịch sử giao hàng</a>
                </li>
                <li>
                    <a href="index.php?action=delivering">Đơn đang giao</a>
                </li>
                <li>
                    <a href="index.php?action=health-history">Thông tin sức khỏe</a>
                </li>
            </ul>

        </div>
    <?php endif ?>
    <?php if (isset($_SESSION["IsLogined"]) && $_SESSION["IsLogined"] == True && $_SESSION["role"] == "shop"): ?>
        <div class="menu">
            <ul>
                <li>
                    <a href="index.php"><br>Trang chủ<br/></a>
                </li>
                <li>
                    <a href="index.php?action=updateShop&role"><br>Cập nhật thông tin Shop<br/></a>
                </li>
                <li>
                    <a href="index.php?action=addProduct"><br>Thêm sản phẩm<br/></a>
                </li>
                <li>
                    <a href="index.php?action=updateProduct"><br>Cập nhật thông tin sản phẩm<br/></a>
                </li>
                <li>
                    <a href="index.php?action=AllProductByShop"><br>Các sản phẩm của shop<br/></a>
                </li>
                <li>
                    <a href="index.php"><br>Tìm kiếm hóa đơn<br/></a>
                </li>
                <li>
                    <a href="index.php"><br>Cập nhật trạng thái hóa đơn<br/></a>
                </li>
            </ul>

        </div>
    <?php endif ?>

    <?php if (isset($_SESSION["IsLogined"]) && $_SESSION["IsLogined"] == True && $_SESSION["role"] == "customer"): ?>
        <div class="menu">
            <ul>
                <li>
                    <a href="index.php"><br>Trang chủ<br/></a>
                </li>
                <li>
                    <a href="index.php?action=customer"><br>Thông tin cá nhân<br/></a>
                </li>
                <li>
                    <a href="index.php?action=customer-products"><br>Sản phẩm<br/></a>
                </li>
                <li>
                <li>
                    <a href="index.php?action=cart"><br>Giỏ hàng<br/></a>
                </li>
                </li>
            </ul>

        </div>
    <?php endif ?>
</div>