
<div class="sidebox">
    <h2>Các chức năng</h2>
    <div class="menu">
        <ul>
            <li>
                <a href="index.php"><br>Trang chủ<br/></a>
            </li>
            <li>
                <a href="index.php?action=updateShop&role"><br>Cập nhật thông tin Shop<br/></a>
            </li>
            <li>
                <a href="index.php?action=addProduct"><br>Thêm sản phẩm<br/></a>
            </li>
            <li>
                <a href="index.php?action=updateProduct"><br>Cập nhật thông tin sản phẩm<br/></a>
                <a href="index.php">Trang chủ</a>
            </li>

        </ul>
  
    </div>
</div>