<h1>TRANG CHỦ</h1>
<hr />

<h1 class="text-3xl font-bold underline">
    Chào mừng bạn đến với ứng dụng Supper Ship
</h1>
<h2>
    Hãy <button class="primary"> <a href="index.php?action=login&role" class="none-decoration" style="color: white">Đăng nhập</a> </button> để bắt đầu sử dụng ứng dụng 
</h2>
<br />

<p>
    Supper Ship là ứng dụng giúp bạn dễ dàng đặt hàng và nhận hàng trong thời gian rất ngắn
    <img src="images/shipper_1.jpeg" width="100%"/>
</p>
<br />

<p>
    Bạn sẽ được thỏa sức mua sắm các món đồ từ những gian hàng đối tác của ứng dụng
</p>
<br />

<img src="images/shopping.jpeg" width="100%"/>

<p>
    Chỉ cần vài thao tác là món đồ của bạn đã đến tay bạn thông qua đội ngũ shipper của chúng tôi
</p>
<br />

<img src="images/shipping2.jpeg" width="100%"/>
