<h1>ĐĂNG NHẬP</h1>
<hr />
<form action="index.php?action=login" method="post">
    <div>
        <span style="display:inline-block; width:200px">Tên đăng nhập:</span> <input name="UserName" type="text" />

    </div>
    <br />
    <div>
        <span style="display:inline-block; width:200px">Mật khẩu: </span> <input name="Password" type="password" />

    </div>
    <br />
    <div ><b style="color: red"><?= $data ?></b></div>
    <br />
    <button class="primary full-width" type="submit">Đăng nhập</button>
</form>