<h1>Cập nhật thông tin Shop</h1>
<hr />
<div>
    <a href="index.php"> <button class="default">Quay lại</button>
    </a>
</div>
<br />
<form action="index.php?action=updateShop&role=shop" method="post" class="mt-24">
    <div class="d-flex align-items-start">
        <span style="display:inline-block; width:200px">Tên cửa hàng: </span> <input name="name" type="text" />
    </div>
    <br />
    <div class="d-flex align-items-start">
        <span style="display:inline-block; width:200px">Địa chỉ: </span> <input name="location" type="text" />
    </div>
    <br />
    <div class="d-flex align-items-start">
        <span style="display:inline-block; width:200px">Mô tả: </span> <textarea name="description"></textarea>
    </div>
    <br />
    <div class="d-flex align-items-start">
        <span style="display:inline-block; width:200px">Số tài khoản ngân hàng: </span> <input name="bank_account" type="text" />
    </div>
    <br />
    <div class="d-flex align-items-start">
        <span style="display:inline-block; width:200px">Số điện thoại: </span> <input name="phone" type="text" />
    </div>
    <br />

    <div><b style="color: red"><?= $data ?></b></div>
    <br />
    <input type="hidden" value=<?= $role ?> />
    <button class="primary full-width" type="submit">Cập Nhật</button>
</form>